Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your github nickname below:

In [ ]:
NICKNAME = "NikitaSadikov"

---

# Задачи по NumPy

In [1]:
import numpy as np
import matplotlib.pyplot as plt

1. Напишите функцию, возвращающую нулевой вектор длины 10, у которого пятый элемент - единица.

*Вектор - numpy массив с shape = (n,)*

In [52]:
def null_vec():
    a = np.zeros(10)
    a[4] = 1
    return a

In [53]:
null_vec()

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2.Верните перевернутый вектор.

Пример: [1, 2, 3]->[3,2,1]

In [54]:
def reverse_vec(v):
    return v[::-1]

In [55]:
reverse_vec(np.array([1, 2, 3, 4]))

array([4, 3, 2, 1])

3.Создайте матрицу 3x3, в которой величины будут идти по порядку от 0 до 8: 

\begin{equation*} 
\begin{pmatrix}
0 & 1 & 2 \\
3 & 4 & 5 \\
6 & 7 & 8 
\end{pmatrix}
\end{equation*}

In [56]:
def matrix():
    return np.arange(9) .reshape(3,3)
matrix()

#Создали массив и распределили по измерениям

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Постройте матрицу размером 8х8 по принципу шахматной доски.

In [57]:
def checkerboard(w, b):
    """Создает матрицу по принципу шахматной доски.
    Parameters
    ----------
    w: Символ, обозначающий белую клетку
    b: Символ, обозначающий черную клетку
    
    Returns
    -------
    m: Матрица 8х8.
    """
    m = np.array([[b,w]*4, [w,b]*4]*4)
    return m

In [58]:
checkerboard(w,b)

array([['b', 'w', 'b', 'w', 'b', 'w', 'b', 'w'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b'],
       ['b', 'w', 'b', 'w', 'b', 'w', 'b', 'w'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b'],
       ['b', 'w', 'b', 'w', 'b', 'w', 'b', 'w'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b'],
       ['b', 'w', 'b', 'w', 'b', 'w', 'b', 'w'],
       ['w', 'b', 'w', 'b', 'w', 'b', 'w', 'b']], dtype='<U1')

5. Напишите функцию, которая переводит декартовы координаты в полярные.

In [61]:
def cartesian_to_polar(c):
    """Переводит массив, состоящий из 10 пар координат xy 
    в массив координат r phi.
    
    Parameters
    ----------
    c: Array of int.
    Массив размерами 10х2, каждая строка -- декартовы координаты точки. 
    
    Returns
    -------
    p: Array of int. 
    Аналогичный массив из пар полярных координат. В первом столбике r.
    """
    p = np.zeros(20).reshape(10,2)
    for i in range(10):
        p[i][0], p[i][1] = np.sqrt(c[i][0]**2 + c[i][1]**2), np.arctan2(c[i][1], c[i][0])
    raise NotImplementedError()
    return p

In [62]:
cartesian_to_polar(c)

NameError: name 'c' is not defined

6. Улитка Пасскаля -- плоская кривая, задаваемая уравнением в полярных координатах: $𝑟=𝑎+cos𝜙.$ 

Напишите функцию, определяющую координаты точек такой кривой.

(Подсказка: np.linspace создает одномерный массив из указанного количества элементов, значения которых равномерно распределенны внутри заданного интервала.)

In [ ]:
def make_curve(n, a):
    '''Функция возвращает массив nх2, содержащий n пар 
    декартовых координат точек кривой Паскаля'''
    # YOUR CODE HERE
    raise NotImplementedError()
    return xy

In [ ]:
N = 50
A = 1
m = make_curve(N, A)

Постройте ее на плоскости xy для разных значений a.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()